{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aerogel",
    "module": "aerogel-gradle-plugin",
    "version": "26.2-27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-27.jar",
          "url": "aerogel-gradle-plugin-26.2-27.jar",
          "size": 81977,
          "sha512": "46cd29aafec84d71f1ea53a8a88bf8af3c06528da8d9c4c9b52c9523749f7c8ba1817012ffe3918960515abdd22b6270d220cbdfe282258cb6dbfcea3176a837",
          "sha256": "87db4efee46a6c6f3e4cecb64980eaa4164af46b9d079fa6daa07e4bb712bace",
          "sha1": "723fd9fedee023d162f65fec0b57b8c4d40a8a72",
          "md5": "f38e3d4ea0d077c3d27da1744d1cea20"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.aerogel",
          "module": "aerogel-api",
          "version": {
            "requires": "26.2-27"
          }
        },
        {
          "group": "dev.aerogel",
          "module": "aerogel-mixin-dsl",
          "version": {
            "requires": "26.2-27"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-27.jar",
          "url": "aerogel-gradle-plugin-26.2-27.jar",
          "size": 81977,
          "sha512": "46cd29aafec84d71f1ea53a8a88bf8af3c06528da8d9c4c9b52c9523749f7c8ba1817012ffe3918960515abdd22b6270d220cbdfe282258cb6dbfcea3176a837",
          "sha256": "87db4efee46a6c6f3e4cecb64980eaa4164af46b9d079fa6daa07e4bb712bace",
          "sha1": "723fd9fedee023d162f65fec0b57b8c4d40a8a72",
          "md5": "f38e3d4ea0d077c3d27da1744d1cea20"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-27-sources.jar",
          "url": "aerogel-gradle-plugin-26.2-27-sources.jar",
          "size": 30550,
          "sha512": "1ee76b029a41fa81a311b97a5b7b0f8b4224911ada63187ba716dc92ffe4c982a44842cec1edbdb413443d73d07cfa8ace9723d30a5a5c6b74ddc01e23331299",
          "sha256": "65c2ab44f0df2d98bb793322e1e0c2f3e7922ca2af9e602727f4789201e27289",
          "sha1": "4c89d0ceec314f78f8e04756a557f470608408a8",
          "md5": "9a6c8402882de39538a32f78fd8ea77a"
        }
      ]
    }
  ]
}
