{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aerogel",
    "module": "aerogel-gradle-plugin",
    "version": "26.2-11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-11.jar",
          "url": "aerogel-gradle-plugin-26.2-11.jar",
          "size": 81977,
          "sha512": "430adf6f1e57212d00fd72d15e5938737e25b14503bfce5c24b8dde7d8c51f3749324b413919347c50b8683463fa06b766b425ef902ac917e290fdc3b9189d26",
          "sha256": "37961021ea4b9874ae0e6722e33998d0ca0df5041d595951459b098a4f26766a",
          "sha1": "20f2af6d957d21e4a837c9ef0b2097398dad5ec3",
          "md5": "4065429bb8ab0e229b8da4c0a7df396f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.aerogel",
          "module": "aerogel-api",
          "version": {
            "requires": "26.2-11"
          }
        },
        {
          "group": "dev.aerogel",
          "module": "aerogel-mixin-dsl",
          "version": {
            "requires": "26.2-11"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-11.jar",
          "url": "aerogel-gradle-plugin-26.2-11.jar",
          "size": 81977,
          "sha512": "430adf6f1e57212d00fd72d15e5938737e25b14503bfce5c24b8dde7d8c51f3749324b413919347c50b8683463fa06b766b425ef902ac917e290fdc3b9189d26",
          "sha256": "37961021ea4b9874ae0e6722e33998d0ca0df5041d595951459b098a4f26766a",
          "sha1": "20f2af6d957d21e4a837c9ef0b2097398dad5ec3",
          "md5": "4065429bb8ab0e229b8da4c0a7df396f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-11-sources.jar",
          "url": "aerogel-gradle-plugin-26.2-11-sources.jar",
          "size": 30550,
          "sha512": "1ee76b029a41fa81a311b97a5b7b0f8b4224911ada63187ba716dc92ffe4c982a44842cec1edbdb413443d73d07cfa8ace9723d30a5a5c6b74ddc01e23331299",
          "sha256": "65c2ab44f0df2d98bb793322e1e0c2f3e7922ca2af9e602727f4789201e27289",
          "sha1": "4c89d0ceec314f78f8e04756a557f470608408a8",
          "md5": "9a6c8402882de39538a32f78fd8ea77a"
        }
      ]
    }
  ]
}
