{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aerogel",
    "module": "aerogel-gradle-plugin",
    "version": "26.2-31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-31.jar",
          "url": "aerogel-gradle-plugin-26.2-31.jar",
          "size": 81977,
          "sha512": "af863b145d19108d33945e5f543fc3afba2213c1cec9e88cf187df757ea28daeb33216b947f3d22012787d200e17f1c26c61866ed1262bf0f8859aa4abd7ee30",
          "sha256": "6e7f336306ce953f635555377fda55facef6b2731629bd63350910c59270720d",
          "sha1": "70379c52799d259faa6f707e693bd825d1e3650c",
          "md5": "6ad910631531668ebd62ec80fdb80b47"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.aerogel",
          "module": "aerogel-api",
          "version": {
            "requires": "26.2-31"
          }
        },
        {
          "group": "dev.aerogel",
          "module": "aerogel-mixin-dsl",
          "version": {
            "requires": "26.2-31"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-31.jar",
          "url": "aerogel-gradle-plugin-26.2-31.jar",
          "size": 81977,
          "sha512": "af863b145d19108d33945e5f543fc3afba2213c1cec9e88cf187df757ea28daeb33216b947f3d22012787d200e17f1c26c61866ed1262bf0f8859aa4abd7ee30",
          "sha256": "6e7f336306ce953f635555377fda55facef6b2731629bd63350910c59270720d",
          "sha1": "70379c52799d259faa6f707e693bd825d1e3650c",
          "md5": "6ad910631531668ebd62ec80fdb80b47"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-31-sources.jar",
          "url": "aerogel-gradle-plugin-26.2-31-sources.jar",
          "size": 30550,
          "sha512": "1ee76b029a41fa81a311b97a5b7b0f8b4224911ada63187ba716dc92ffe4c982a44842cec1edbdb413443d73d07cfa8ace9723d30a5a5c6b74ddc01e23331299",
          "sha256": "65c2ab44f0df2d98bb793322e1e0c2f3e7922ca2af9e602727f4789201e27289",
          "sha1": "4c89d0ceec314f78f8e04756a557f470608408a8",
          "md5": "9a6c8402882de39538a32f78fd8ea77a"
        }
      ]
    }
  ]
}
