{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aerogel",
    "module": "aerogel-api",
    "version": "26.2-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aerogel-api-26.2-1.jar",
          "url": "aerogel-api-26.2-1.jar",
          "size": 156806,
          "sha512": "2e38314ceacdaf40a1d7e393a654eda7857ea006bc88cd572622ee8491b35ce5b5e47e8e12ccf1e724a826528e814d4cffb6bb042f5d631a2a4eee9650025b83",
          "sha256": "d6f012ed30470216581141143e7ffdff3aa9c331433e911a73590ca29d2587a7",
          "sha1": "fa4da5208ce459eb895928142d022119b8b664ed",
          "md5": "992960fdfc136fde44f39baf25e9692a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-api-26.2-1.jar",
          "url": "aerogel-api-26.2-1.jar",
          "size": 156806,
          "sha512": "2e38314ceacdaf40a1d7e393a654eda7857ea006bc88cd572622ee8491b35ce5b5e47e8e12ccf1e724a826528e814d4cffb6bb042f5d631a2a4eee9650025b83",
          "sha256": "d6f012ed30470216581141143e7ffdff3aa9c331433e911a73590ca29d2587a7",
          "sha1": "fa4da5208ce459eb895928142d022119b8b664ed",
          "md5": "992960fdfc136fde44f39baf25e9692a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-api-26.2-1-sources.jar",
          "url": "aerogel-api-26.2-1-sources.jar",
          "size": 94216,
          "sha512": "a56ff6fb028159f183f8291fd6914d6fc6b8b0ad5ad1e48b5d9ddfebc47df85baeabc97d978487e30456c4d330864db2ac79b1e34b09ef1a4e57af050d15aba7",
          "sha256": "73d39364de21d8b99bd2708d37a4ed4409aaa2cd028e8686c04147f86cbc9c71",
          "sha1": "87c57807a5273970ffbce2a17c3ce2b9098fd3c9",
          "md5": "55df088f6b69ecd3dbb8f91fd1f2d8a5"
        }
      ]
    }
  ]
}
