{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aerogel",
    "module": "aerogel-api",
    "version": "26.2-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aerogel-api-26.2-1.jar",
          "url": "aerogel-api-26.2-1.jar",
          "size": 132400,
          "sha512": "a70ee7abf95cde775829f26c6feac4155bd819ecde1757d491b841bb0f6cd0dd1354a26daa1580e2fffa85d311b5430128c3e3fd356a17fe4d279d40727b1781",
          "sha256": "72fc17b0fd1444ac17b7559596f0f46d446654d4fd66eadeac864b794472d473",
          "sha1": "b86fc9492640e2754593ccfe35838afc5bcbce0a",
          "md5": "9b7c2a44c43c0050c78b6a8964f0d5c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-api-26.2-1.jar",
          "url": "aerogel-api-26.2-1.jar",
          "size": 132400,
          "sha512": "a70ee7abf95cde775829f26c6feac4155bd819ecde1757d491b841bb0f6cd0dd1354a26daa1580e2fffa85d311b5430128c3e3fd356a17fe4d279d40727b1781",
          "sha256": "72fc17b0fd1444ac17b7559596f0f46d446654d4fd66eadeac864b794472d473",
          "sha1": "b86fc9492640e2754593ccfe35838afc5bcbce0a",
          "md5": "9b7c2a44c43c0050c78b6a8964f0d5c5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-api-26.2-1-sources.jar",
          "url": "aerogel-api-26.2-1-sources.jar",
          "size": 84463,
          "sha512": "b386ac23c78e2029da6004c5a2a400239105880f1fe08a5a89ad53ab7a2549083aa87a0cb748638f22dd15e441bc1110400bbae6d8818711075d50faff189780",
          "sha256": "27ddfe19c8807047e766273e8ebe9a16839c12da6d8c084fe8965c1f041b14c1",
          "sha1": "7b7dde711f806a97e06ec257dc28d834a4000471",
          "md5": "871f2a043e43e2240a8a84a8255dc7d4"
        }
      ]
    }
  ]
}
