{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aerogel",
    "module": "aerogel-gradle-plugin",
    "version": "26.2-17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-17.jar",
          "url": "aerogel-gradle-plugin-26.2-17.jar",
          "size": 81977,
          "sha512": "0b6e3c08145b62e4f6d5264ecc19b2bab5cbb8252d134ec11bbc2eea2f8ba2ee0754422454bdcdc1ff94dfa1f8ebab6c871ce8652399eed65d376e31724a25e6",
          "sha256": "b14819203819c25f3d8e1ebcf7678ca2ffdd17c9262475342df97407e33d23b4",
          "sha1": "a3f6f63ec604cd4ca1dc90ec653876f201b24bfa",
          "md5": "dbbd86794ff06d2c245430989746229f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.aerogel",
          "module": "aerogel-api",
          "version": {
            "requires": "26.2-17"
          }
        },
        {
          "group": "dev.aerogel",
          "module": "aerogel-mixin-dsl",
          "version": {
            "requires": "26.2-17"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-17.jar",
          "url": "aerogel-gradle-plugin-26.2-17.jar",
          "size": 81977,
          "sha512": "0b6e3c08145b62e4f6d5264ecc19b2bab5cbb8252d134ec11bbc2eea2f8ba2ee0754422454bdcdc1ff94dfa1f8ebab6c871ce8652399eed65d376e31724a25e6",
          "sha256": "b14819203819c25f3d8e1ebcf7678ca2ffdd17c9262475342df97407e33d23b4",
          "sha1": "a3f6f63ec604cd4ca1dc90ec653876f201b24bfa",
          "md5": "dbbd86794ff06d2c245430989746229f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-17-sources.jar",
          "url": "aerogel-gradle-plugin-26.2-17-sources.jar",
          "size": 30550,
          "sha512": "1ee76b029a41fa81a311b97a5b7b0f8b4224911ada63187ba716dc92ffe4c982a44842cec1edbdb413443d73d07cfa8ace9723d30a5a5c6b74ddc01e23331299",
          "sha256": "65c2ab44f0df2d98bb793322e1e0c2f3e7922ca2af9e602727f4789201e27289",
          "sha1": "4c89d0ceec314f78f8e04756a557f470608408a8",
          "md5": "9a6c8402882de39538a32f78fd8ea77a"
        }
      ]
    }
  ]
}
