{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aerogel",
    "module": "aerogel-gradle-plugin",
    "version": "26.2-23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-23.jar",
          "url": "aerogel-gradle-plugin-26.2-23.jar",
          "size": 81977,
          "sha512": "8419cd60e4960492dd0d8569541a51469d00f415aeb8a1490b934cfc8ecd6c47a2d47f5198011fa33cae46026aa6ba7158fa6bb9f2c3e743ff1679984a5d668c",
          "sha256": "ba66d662b7e26ee5c7e5f1640140f87f2d0935393060564550044a8299dfb5cf",
          "sha1": "d4da4a9c23879ce5a725c6e79b04e5b9fca1adf6",
          "md5": "35c22368621d198bc7c0ce491487547a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.aerogel",
          "module": "aerogel-api",
          "version": {
            "requires": "26.2-23"
          }
        },
        {
          "group": "dev.aerogel",
          "module": "aerogel-mixin-dsl",
          "version": {
            "requires": "26.2-23"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-23.jar",
          "url": "aerogel-gradle-plugin-26.2-23.jar",
          "size": 81977,
          "sha512": "8419cd60e4960492dd0d8569541a51469d00f415aeb8a1490b934cfc8ecd6c47a2d47f5198011fa33cae46026aa6ba7158fa6bb9f2c3e743ff1679984a5d668c",
          "sha256": "ba66d662b7e26ee5c7e5f1640140f87f2d0935393060564550044a8299dfb5cf",
          "sha1": "d4da4a9c23879ce5a725c6e79b04e5b9fca1adf6",
          "md5": "35c22368621d198bc7c0ce491487547a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-23-sources.jar",
          "url": "aerogel-gradle-plugin-26.2-23-sources.jar",
          "size": 30550,
          "sha512": "1ee76b029a41fa81a311b97a5b7b0f8b4224911ada63187ba716dc92ffe4c982a44842cec1edbdb413443d73d07cfa8ace9723d30a5a5c6b74ddc01e23331299",
          "sha256": "65c2ab44f0df2d98bb793322e1e0c2f3e7922ca2af9e602727f4789201e27289",
          "sha1": "4c89d0ceec314f78f8e04756a557f470608408a8",
          "md5": "9a6c8402882de39538a32f78fd8ea77a"
        }
      ]
    }
  ]
}
