{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aerogel",
    "module": "aerogel-gradle-plugin",
    "version": "26.2-29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-29.jar",
          "url": "aerogel-gradle-plugin-26.2-29.jar",
          "size": 81977,
          "sha512": "28aa38896b01a153f3b1c7b81a4c75723bdb6a5b962c3c51ed8d65d0c6a6ad1cef8058308c1d78bb91741d1a993aa6d4b0c251871498939d12931213379f7bcb",
          "sha256": "ecd3f3a578e264e931f08945e93a80428fc0a13362a548931809e099f7536be2",
          "sha1": "de82b0215d94f14a4efef3b202695419dec8026b",
          "md5": "f23589a076e3f21ced149965a1a7b32d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.aerogel",
          "module": "aerogel-api",
          "version": {
            "requires": "26.2-29"
          }
        },
        {
          "group": "dev.aerogel",
          "module": "aerogel-mixin-dsl",
          "version": {
            "requires": "26.2-29"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-29.jar",
          "url": "aerogel-gradle-plugin-26.2-29.jar",
          "size": 81977,
          "sha512": "28aa38896b01a153f3b1c7b81a4c75723bdb6a5b962c3c51ed8d65d0c6a6ad1cef8058308c1d78bb91741d1a993aa6d4b0c251871498939d12931213379f7bcb",
          "sha256": "ecd3f3a578e264e931f08945e93a80428fc0a13362a548931809e099f7536be2",
          "sha1": "de82b0215d94f14a4efef3b202695419dec8026b",
          "md5": "f23589a076e3f21ced149965a1a7b32d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-29-sources.jar",
          "url": "aerogel-gradle-plugin-26.2-29-sources.jar",
          "size": 30550,
          "sha512": "1ee76b029a41fa81a311b97a5b7b0f8b4224911ada63187ba716dc92ffe4c982a44842cec1edbdb413443d73d07cfa8ace9723d30a5a5c6b74ddc01e23331299",
          "sha256": "65c2ab44f0df2d98bb793322e1e0c2f3e7922ca2af9e602727f4789201e27289",
          "sha1": "4c89d0ceec314f78f8e04756a557f470608408a8",
          "md5": "9a6c8402882de39538a32f78fd8ea77a"
        }
      ]
    }
  ]
}
