{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aerogel",
    "module": "aerogel-gradle-plugin",
    "version": "26.2-8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-8.jar",
          "url": "aerogel-gradle-plugin-26.2-8.jar",
          "size": 81976,
          "sha512": "c28cdedce5c7fc8cf1a68834e0bbfdfe6d1507f04039670bc5946a5f0e79d08ab9f898dadd3118a5ca280a81699dc517f7e93be8b09b1c4ad0e93c17fba963aa",
          "sha256": "de01d06c158d3075d277cd7ae4ba96d2c79356d1960e643bff4ce58c6ff7473b",
          "sha1": "6d2f7ae64f8f57b607da8cc6849cb3fe8ab01426",
          "md5": "df10945f8904a88b0326368fc785a784"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.aerogel",
          "module": "aerogel-api",
          "version": {
            "requires": "26.2-8"
          }
        },
        {
          "group": "dev.aerogel",
          "module": "aerogel-mixin-dsl",
          "version": {
            "requires": "26.2-8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-8.jar",
          "url": "aerogel-gradle-plugin-26.2-8.jar",
          "size": 81976,
          "sha512": "c28cdedce5c7fc8cf1a68834e0bbfdfe6d1507f04039670bc5946a5f0e79d08ab9f898dadd3118a5ca280a81699dc517f7e93be8b09b1c4ad0e93c17fba963aa",
          "sha256": "de01d06c158d3075d277cd7ae4ba96d2c79356d1960e643bff4ce58c6ff7473b",
          "sha1": "6d2f7ae64f8f57b607da8cc6849cb3fe8ab01426",
          "md5": "df10945f8904a88b0326368fc785a784"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-8-sources.jar",
          "url": "aerogel-gradle-plugin-26.2-8-sources.jar",
          "size": 30550,
          "sha512": "1ee76b029a41fa81a311b97a5b7b0f8b4224911ada63187ba716dc92ffe4c982a44842cec1edbdb413443d73d07cfa8ace9723d30a5a5c6b74ddc01e23331299",
          "sha256": "65c2ab44f0df2d98bb793322e1e0c2f3e7922ca2af9e602727f4789201e27289",
          "sha1": "4c89d0ceec314f78f8e04756a557f470608408a8",
          "md5": "9a6c8402882de39538a32f78fd8ea77a"
        }
      ]
    }
  ]
}
