{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aerogel",
    "module": "aerogel-gradle-plugin",
    "version": "26.2-25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-25.jar",
          "url": "aerogel-gradle-plugin-26.2-25.jar",
          "size": 81977,
          "sha512": "8d8d40668c500dabe40ff75f6a2804e8821943d1085725b0d1bc0513247bdd9b3142e0ef69901efb3153c9acb039b75aa9a3cdd48a44ba8a1802fa1e7c4e14e4",
          "sha256": "8a6e2794a286e89df2e5456ed589e1053c7becd268180edcb8e99b00828024ea",
          "sha1": "4de7f3e4e71c3ef521248a30050a00fa6569ca00",
          "md5": "d4a3e13d8a13dfde2e68881867437a6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.aerogel",
          "module": "aerogel-api",
          "version": {
            "requires": "26.2-25"
          }
        },
        {
          "group": "dev.aerogel",
          "module": "aerogel-mixin-dsl",
          "version": {
            "requires": "26.2-25"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-25.jar",
          "url": "aerogel-gradle-plugin-26.2-25.jar",
          "size": 81977,
          "sha512": "8d8d40668c500dabe40ff75f6a2804e8821943d1085725b0d1bc0513247bdd9b3142e0ef69901efb3153c9acb039b75aa9a3cdd48a44ba8a1802fa1e7c4e14e4",
          "sha256": "8a6e2794a286e89df2e5456ed589e1053c7becd268180edcb8e99b00828024ea",
          "sha1": "4de7f3e4e71c3ef521248a30050a00fa6569ca00",
          "md5": "d4a3e13d8a13dfde2e68881867437a6a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-25-sources.jar",
          "url": "aerogel-gradle-plugin-26.2-25-sources.jar",
          "size": 30550,
          "sha512": "1ee76b029a41fa81a311b97a5b7b0f8b4224911ada63187ba716dc92ffe4c982a44842cec1edbdb413443d73d07cfa8ace9723d30a5a5c6b74ddc01e23331299",
          "sha256": "65c2ab44f0df2d98bb793322e1e0c2f3e7922ca2af9e602727f4789201e27289",
          "sha1": "4c89d0ceec314f78f8e04756a557f470608408a8",
          "md5": "9a6c8402882de39538a32f78fd8ea77a"
        }
      ]
    }
  ]
}
