{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aerogel",
    "module": "aerogel-gradle-plugin",
    "version": "26.2-14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-14.jar",
          "url": "aerogel-gradle-plugin-26.2-14.jar",
          "size": 81977,
          "sha512": "f6978c4be1a3460907a75d23aac3ae32c9b9b2a347555904da3b959a13669aa92c25d270d0ee081362672f0222df83cdc05bdd86d5e85e5e246a1281745435ae",
          "sha256": "58baac2e95cb15a14c7b0f8f70832ec5e7e1926c2bd95351ab986bb3a61077e4",
          "sha1": "444dcc5b4c997961f7e3c96a69d1f8483c64a639",
          "md5": "d50c9568b45685a7927ced331b131aa4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.aerogel",
          "module": "aerogel-api",
          "version": {
            "requires": "26.2-14"
          }
        },
        {
          "group": "dev.aerogel",
          "module": "aerogel-mixin-dsl",
          "version": {
            "requires": "26.2-14"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-14.jar",
          "url": "aerogel-gradle-plugin-26.2-14.jar",
          "size": 81977,
          "sha512": "f6978c4be1a3460907a75d23aac3ae32c9b9b2a347555904da3b959a13669aa92c25d270d0ee081362672f0222df83cdc05bdd86d5e85e5e246a1281745435ae",
          "sha256": "58baac2e95cb15a14c7b0f8f70832ec5e7e1926c2bd95351ab986bb3a61077e4",
          "sha1": "444dcc5b4c997961f7e3c96a69d1f8483c64a639",
          "md5": "d50c9568b45685a7927ced331b131aa4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-14-sources.jar",
          "url": "aerogel-gradle-plugin-26.2-14-sources.jar",
          "size": 30550,
          "sha512": "1ee76b029a41fa81a311b97a5b7b0f8b4224911ada63187ba716dc92ffe4c982a44842cec1edbdb413443d73d07cfa8ace9723d30a5a5c6b74ddc01e23331299",
          "sha256": "65c2ab44f0df2d98bb793322e1e0c2f3e7922ca2af9e602727f4789201e27289",
          "sha1": "4c89d0ceec314f78f8e04756a557f470608408a8",
          "md5": "9a6c8402882de39538a32f78fd8ea77a"
        }
      ]
    }
  ]
}
