{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aerogel",
    "module": "aerogel-mixin-dsl",
    "version": "26.2-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "aerogel-mixin-dsl-26.2-1.jar",
          "url": "aerogel-mixin-dsl-26.2-1.jar",
          "size": 94500,
          "sha512": "9d775042cc1a2f578b9ef00b8c4cca8e8b2957ce05a8778fa507c435597c414ac6fba8b990942966b3223c08582936bdecf0ca69b11bcb3ce0e1b2286b859257",
          "sha256": "21e9088e7fbc58bb44fa0ebf92ac73ad43f89d9fac6aa7b5602a9d1e7bdcf9ea",
          "sha1": "9ad903bb3321f07288a0f7db4b4ee1d008b022f9",
          "md5": "2245faa94502699ccc15a1885eccf80d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-common"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-jvm"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-common",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-jvm",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "aerogel-mixin-dsl-26.2-1.jar",
          "url": "aerogel-mixin-dsl-26.2-1.jar",
          "size": 94500,
          "sha512": "9d775042cc1a2f578b9ef00b8c4cca8e8b2957ce05a8778fa507c435597c414ac6fba8b990942966b3223c08582936bdecf0ca69b11bcb3ce0e1b2286b859257",
          "sha256": "21e9088e7fbc58bb44fa0ebf92ac73ad43f89d9fac6aa7b5602a9d1e7bdcf9ea",
          "sha1": "9ad903bb3321f07288a0f7db4b4ee1d008b022f9",
          "md5": "2245faa94502699ccc15a1885eccf80d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-mixin-dsl-26.2-1-sources.jar",
          "url": "aerogel-mixin-dsl-26.2-1-sources.jar",
          "size": 10273,
          "sha512": "ad12f47bba65556c43bb270138f86338b06887c1601826f7c1393cfbf446ab536d65c9f5645dce9434eb157f2fb4280a214db95c1f0bac6d70d1f2e6484cd139",
          "sha256": "81a545fa790404d0d801bbd9d7d78328dd7cb10a7a4d26cb76792e4d364250d4",
          "sha1": "97ae184d4760c196b2987402d3ebd5fcea6ebf32",
          "md5": "3ffc2098ebddeefeef82db6ee294932b"
        },
        {
          "name": "aerogel-mixin-dsl-26.2-1-sources.jar",
          "url": "aerogel-mixin-dsl-26.2-1-sources.jar",
          "size": 10273,
          "sha512": "ad12f47bba65556c43bb270138f86338b06887c1601826f7c1393cfbf446ab536d65c9f5645dce9434eb157f2fb4280a214db95c1f0bac6d70d1f2e6484cd139",
          "sha256": "81a545fa790404d0d801bbd9d7d78328dd7cb10a7a4d26cb76792e4d364250d4",
          "sha1": "97ae184d4760c196b2987402d3ebd5fcea6ebf32",
          "md5": "3ffc2098ebddeefeef82db6ee294932b"
        }
      ]
    }
  ]
}
