{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aerogel",
    "module": "aerogel-gradle-plugin",
    "version": "26.2-5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-5.jar",
          "url": "aerogel-gradle-plugin-26.2-5.jar",
          "size": 81976,
          "sha512": "53c452bb6b928f8563cb535712acee070350475f8bc5d32ac6cb55dc10f3391ac15db5312c2a5e89f9dfaf8fa57ad5ccc24c06aa41c4d6d7cf2e7cd8a0947140",
          "sha256": "50e1a68e28089e5d904cfb2d65d3248e28bdcafc990c6ed74d4e6895f6d85964",
          "sha1": "e5a5c95a502d25a1e5e1e4f33af73c83b8c00571",
          "md5": "f75dc811c1665c07da5136edc83300e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.aerogel",
          "module": "aerogel-api",
          "version": {
            "requires": "26.2-5"
          }
        },
        {
          "group": "dev.aerogel",
          "module": "aerogel-mixin-dsl",
          "version": {
            "requires": "26.2-5"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-5.jar",
          "url": "aerogel-gradle-plugin-26.2-5.jar",
          "size": 81976,
          "sha512": "53c452bb6b928f8563cb535712acee070350475f8bc5d32ac6cb55dc10f3391ac15db5312c2a5e89f9dfaf8fa57ad5ccc24c06aa41c4d6d7cf2e7cd8a0947140",
          "sha256": "50e1a68e28089e5d904cfb2d65d3248e28bdcafc990c6ed74d4e6895f6d85964",
          "sha1": "e5a5c95a502d25a1e5e1e4f33af73c83b8c00571",
          "md5": "f75dc811c1665c07da5136edc83300e7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-5-sources.jar",
          "url": "aerogel-gradle-plugin-26.2-5-sources.jar",
          "size": 30550,
          "sha512": "1ee76b029a41fa81a311b97a5b7b0f8b4224911ada63187ba716dc92ffe4c982a44842cec1edbdb413443d73d07cfa8ace9723d30a5a5c6b74ddc01e23331299",
          "sha256": "65c2ab44f0df2d98bb793322e1e0c2f3e7922ca2af9e602727f4789201e27289",
          "sha1": "4c89d0ceec314f78f8e04756a557f470608408a8",
          "md5": "9a6c8402882de39538a32f78fd8ea77a"
        }
      ]
    }
  ]
}
