{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aerogel",
    "module": "aerogel-gradle-plugin",
    "version": "26.2-6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-6.jar",
          "url": "aerogel-gradle-plugin-26.2-6.jar",
          "size": 81976,
          "sha512": "ba5a4953fe9a848b09b2040e266a054727f31471c144117f6da8d0457402557e418681cf273356195486defefadec82b05289cb6ddb178e3a416cd691d497d36",
          "sha256": "33b275d7af29ace1892114838640ed853c22794d4546fac5afe1602deb3b788b",
          "sha1": "8e5ea3ac59e7ddceca6d9565eec640b99adbe0b0",
          "md5": "0801b3a4bfd666f3a5ff4ffcf700c9aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.aerogel",
          "module": "aerogel-api",
          "version": {
            "requires": "26.2-6"
          }
        },
        {
          "group": "dev.aerogel",
          "module": "aerogel-mixin-dsl",
          "version": {
            "requires": "26.2-6"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-6.jar",
          "url": "aerogel-gradle-plugin-26.2-6.jar",
          "size": 81976,
          "sha512": "ba5a4953fe9a848b09b2040e266a054727f31471c144117f6da8d0457402557e418681cf273356195486defefadec82b05289cb6ddb178e3a416cd691d497d36",
          "sha256": "33b275d7af29ace1892114838640ed853c22794d4546fac5afe1602deb3b788b",
          "sha1": "8e5ea3ac59e7ddceca6d9565eec640b99adbe0b0",
          "md5": "0801b3a4bfd666f3a5ff4ffcf700c9aa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-6-sources.jar",
          "url": "aerogel-gradle-plugin-26.2-6-sources.jar",
          "size": 30550,
          "sha512": "1ee76b029a41fa81a311b97a5b7b0f8b4224911ada63187ba716dc92ffe4c982a44842cec1edbdb413443d73d07cfa8ace9723d30a5a5c6b74ddc01e23331299",
          "sha256": "65c2ab44f0df2d98bb793322e1e0c2f3e7922ca2af9e602727f4789201e27289",
          "sha1": "4c89d0ceec314f78f8e04756a557f470608408a8",
          "md5": "9a6c8402882de39538a32f78fd8ea77a"
        }
      ]
    }
  ]
}
