{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aerogel",
    "module": "aerogel-gradle-plugin",
    "version": "26.2-12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-12.jar",
          "url": "aerogel-gradle-plugin-26.2-12.jar",
          "size": 81977,
          "sha512": "57c8fff94a3659149814705a19a0334fa1219295b40fe90a4e7e8ba39e14e7101879eb5d49009dea616071318e2c98a8600d574bb9d99b87443b344843ea1b57",
          "sha256": "41c573afe210206ad3bf6c6ce7742bbeada7e26fa623fa88654b5af322009864",
          "sha1": "8c955dbf89cc9aed0b47659155f78a0cb3a63245",
          "md5": "8d9af958b6aa87addd4ee72a6cc13f25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.aerogel",
          "module": "aerogel-api",
          "version": {
            "requires": "26.2-12"
          }
        },
        {
          "group": "dev.aerogel",
          "module": "aerogel-mixin-dsl",
          "version": {
            "requires": "26.2-12"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-12.jar",
          "url": "aerogel-gradle-plugin-26.2-12.jar",
          "size": 81977,
          "sha512": "57c8fff94a3659149814705a19a0334fa1219295b40fe90a4e7e8ba39e14e7101879eb5d49009dea616071318e2c98a8600d574bb9d99b87443b344843ea1b57",
          "sha256": "41c573afe210206ad3bf6c6ce7742bbeada7e26fa623fa88654b5af322009864",
          "sha1": "8c955dbf89cc9aed0b47659155f78a0cb3a63245",
          "md5": "8d9af958b6aa87addd4ee72a6cc13f25"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-12-sources.jar",
          "url": "aerogel-gradle-plugin-26.2-12-sources.jar",
          "size": 30550,
          "sha512": "1ee76b029a41fa81a311b97a5b7b0f8b4224911ada63187ba716dc92ffe4c982a44842cec1edbdb413443d73d07cfa8ace9723d30a5a5c6b74ddc01e23331299",
          "sha256": "65c2ab44f0df2d98bb793322e1e0c2f3e7922ca2af9e602727f4789201e27289",
          "sha1": "4c89d0ceec314f78f8e04756a557f470608408a8",
          "md5": "9a6c8402882de39538a32f78fd8ea77a"
        }
      ]
    }
  ]
}
