{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aerogel",
    "module": "aerogel-gradle-plugin",
    "version": "26.2-24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-24.jar",
          "url": "aerogel-gradle-plugin-26.2-24.jar",
          "size": 81977,
          "sha512": "b8c58b4bd4328bf75f648ec6d7e092ce4ac82696839d7e5e5f46f2145d122ed46bc8f687f43728128b66493458cc56413b2717d466c8f44e8c65392959db38e7",
          "sha256": "316c2fda80a37b2f8fde37deaaaf551510ff194115666b4d715aed1a51fa44f5",
          "sha1": "caa8a2991f84d5c86cb1fbead47d98a4258f9087",
          "md5": "7b7eb093d6530158b46ca0a6b1e17434"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.aerogel",
          "module": "aerogel-api",
          "version": {
            "requires": "26.2-24"
          }
        },
        {
          "group": "dev.aerogel",
          "module": "aerogel-mixin-dsl",
          "version": {
            "requires": "26.2-24"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-24.jar",
          "url": "aerogel-gradle-plugin-26.2-24.jar",
          "size": 81977,
          "sha512": "b8c58b4bd4328bf75f648ec6d7e092ce4ac82696839d7e5e5f46f2145d122ed46bc8f687f43728128b66493458cc56413b2717d466c8f44e8c65392959db38e7",
          "sha256": "316c2fda80a37b2f8fde37deaaaf551510ff194115666b4d715aed1a51fa44f5",
          "sha1": "caa8a2991f84d5c86cb1fbead47d98a4258f9087",
          "md5": "7b7eb093d6530158b46ca0a6b1e17434"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-24-sources.jar",
          "url": "aerogel-gradle-plugin-26.2-24-sources.jar",
          "size": 30550,
          "sha512": "1ee76b029a41fa81a311b97a5b7b0f8b4224911ada63187ba716dc92ffe4c982a44842cec1edbdb413443d73d07cfa8ace9723d30a5a5c6b74ddc01e23331299",
          "sha256": "65c2ab44f0df2d98bb793322e1e0c2f3e7922ca2af9e602727f4789201e27289",
          "sha1": "4c89d0ceec314f78f8e04756a557f470608408a8",
          "md5": "9a6c8402882de39538a32f78fd8ea77a"
        }
      ]
    }
  ]
}
