{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aerogel",
    "module": "aerogel-gradle-plugin",
    "version": "26.2-22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-22.jar",
          "url": "aerogel-gradle-plugin-26.2-22.jar",
          "size": 81977,
          "sha512": "eae74de50a20c6fb48dead70a1e327614f1779a4b7ac1f0dda09683a03cce92b791395abc586d8c09ef5785543c9d544e455a1f67b6c9b222b80e9cbb2500ca5",
          "sha256": "fa52359ed0ff978d1dcb25f91ecc60b0f0d2b1e7d5f0dbe2b3214ddb0afdf7f8",
          "sha1": "92523901b4ac77879d39bd778ac2a3d6673e59ea",
          "md5": "f837483f8729028a58f47ff88ef369b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.aerogel",
          "module": "aerogel-api",
          "version": {
            "requires": "26.2-22"
          }
        },
        {
          "group": "dev.aerogel",
          "module": "aerogel-mixin-dsl",
          "version": {
            "requires": "26.2-22"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-22.jar",
          "url": "aerogel-gradle-plugin-26.2-22.jar",
          "size": 81977,
          "sha512": "eae74de50a20c6fb48dead70a1e327614f1779a4b7ac1f0dda09683a03cce92b791395abc586d8c09ef5785543c9d544e455a1f67b6c9b222b80e9cbb2500ca5",
          "sha256": "fa52359ed0ff978d1dcb25f91ecc60b0f0d2b1e7d5f0dbe2b3214ddb0afdf7f8",
          "sha1": "92523901b4ac77879d39bd778ac2a3d6673e59ea",
          "md5": "f837483f8729028a58f47ff88ef369b7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-22-sources.jar",
          "url": "aerogel-gradle-plugin-26.2-22-sources.jar",
          "size": 30550,
          "sha512": "1ee76b029a41fa81a311b97a5b7b0f8b4224911ada63187ba716dc92ffe4c982a44842cec1edbdb413443d73d07cfa8ace9723d30a5a5c6b74ddc01e23331299",
          "sha256": "65c2ab44f0df2d98bb793322e1e0c2f3e7922ca2af9e602727f4789201e27289",
          "sha1": "4c89d0ceec314f78f8e04756a557f470608408a8",
          "md5": "9a6c8402882de39538a32f78fd8ea77a"
        }
      ]
    }
  ]
}
