{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aerogel",
    "module": "aerogel-gradle-plugin",
    "version": "26.2-13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-13.jar",
          "url": "aerogel-gradle-plugin-26.2-13.jar",
          "size": 81977,
          "sha512": "3dd4e255e8c684dcc85f5803fa94a500b11e4a81d0e8478a1fdd3aa9348b123cfec2b90f37040d213f15b04253f9204434a843808dbe98c37a7290ee9be02bd3",
          "sha256": "9008fbf3fc13c554224fb80f59423dd78cce0e6f8296e4e84e57208a470c69b0",
          "sha1": "1af8d1c203fa9190a7a25778b47733cb0949c0c6",
          "md5": "5e73eab2eb353524ec6a9b9f152e8627"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.aerogel",
          "module": "aerogel-api",
          "version": {
            "requires": "26.2-13"
          }
        },
        {
          "group": "dev.aerogel",
          "module": "aerogel-mixin-dsl",
          "version": {
            "requires": "26.2-13"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-13.jar",
          "url": "aerogel-gradle-plugin-26.2-13.jar",
          "size": 81977,
          "sha512": "3dd4e255e8c684dcc85f5803fa94a500b11e4a81d0e8478a1fdd3aa9348b123cfec2b90f37040d213f15b04253f9204434a843808dbe98c37a7290ee9be02bd3",
          "sha256": "9008fbf3fc13c554224fb80f59423dd78cce0e6f8296e4e84e57208a470c69b0",
          "sha1": "1af8d1c203fa9190a7a25778b47733cb0949c0c6",
          "md5": "5e73eab2eb353524ec6a9b9f152e8627"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-13-sources.jar",
          "url": "aerogel-gradle-plugin-26.2-13-sources.jar",
          "size": 30550,
          "sha512": "1ee76b029a41fa81a311b97a5b7b0f8b4224911ada63187ba716dc92ffe4c982a44842cec1edbdb413443d73d07cfa8ace9723d30a5a5c6b74ddc01e23331299",
          "sha256": "65c2ab44f0df2d98bb793322e1e0c2f3e7922ca2af9e602727f4789201e27289",
          "sha1": "4c89d0ceec314f78f8e04756a557f470608408a8",
          "md5": "9a6c8402882de39538a32f78fd8ea77a"
        }
      ]
    }
  ]
}
