{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aerogel",
    "module": "aerogel-gradle-plugin",
    "version": "26.2-26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-26.jar",
          "url": "aerogel-gradle-plugin-26.2-26.jar",
          "size": 81977,
          "sha512": "fe73499972bae8a0659f2506471bf13aa788ba31cff1b064351c3e4ecdce47193cd48be269bdca2381d9e91fa6a1cb8f87147ddeadcce052e0e6573aed36e341",
          "sha256": "4bf043d3770973ae715035070c057ac8c827c43ad22bf2680184c5874db1c2f6",
          "sha1": "bfc43a9937319c9ccedb3905cdb238070bfa008d",
          "md5": "635642594d38861960a1730305242d80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.aerogel",
          "module": "aerogel-api",
          "version": {
            "requires": "26.2-26"
          }
        },
        {
          "group": "dev.aerogel",
          "module": "aerogel-mixin-dsl",
          "version": {
            "requires": "26.2-26"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-26.jar",
          "url": "aerogel-gradle-plugin-26.2-26.jar",
          "size": 81977,
          "sha512": "fe73499972bae8a0659f2506471bf13aa788ba31cff1b064351c3e4ecdce47193cd48be269bdca2381d9e91fa6a1cb8f87147ddeadcce052e0e6573aed36e341",
          "sha256": "4bf043d3770973ae715035070c057ac8c827c43ad22bf2680184c5874db1c2f6",
          "sha1": "bfc43a9937319c9ccedb3905cdb238070bfa008d",
          "md5": "635642594d38861960a1730305242d80"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-26-sources.jar",
          "url": "aerogel-gradle-plugin-26.2-26-sources.jar",
          "size": 30550,
          "sha512": "1ee76b029a41fa81a311b97a5b7b0f8b4224911ada63187ba716dc92ffe4c982a44842cec1edbdb413443d73d07cfa8ace9723d30a5a5c6b74ddc01e23331299",
          "sha256": "65c2ab44f0df2d98bb793322e1e0c2f3e7922ca2af9e602727f4789201e27289",
          "sha1": "4c89d0ceec314f78f8e04756a557f470608408a8",
          "md5": "9a6c8402882de39538a32f78fd8ea77a"
        }
      ]
    }
  ]
}
