{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aerogel",
    "module": "aerogel-gradle-plugin",
    "version": "26.2-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-1.jar",
          "url": "aerogel-gradle-plugin-26.2-1.jar",
          "size": 81721,
          "sha512": "9b3b2372ef87618b105855cbf2eddebec9c18d4cf75fe9cd53ad89cb9c5880d144d4153265fe7e3e97e9fa1eea0ee02cbe7ce7bdda037888c11bd2d24f26c43b",
          "sha256": "3c2ff961a30f3a4562244c3aaf27bcadd67095f14c70ed4978638d825274f002",
          "sha1": "0394aa0285e4f81896151a39584c09284c967a4a",
          "md5": "fb68412a18169aaa56978cbb42da3ebd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.aerogel",
          "module": "aerogel-api",
          "version": {
            "requires": "26.2-1"
          }
        },
        {
          "group": "dev.aerogel",
          "module": "aerogel-mixin-dsl",
          "version": {
            "requires": "26.2-1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-1.jar",
          "url": "aerogel-gradle-plugin-26.2-1.jar",
          "size": 81721,
          "sha512": "9b3b2372ef87618b105855cbf2eddebec9c18d4cf75fe9cd53ad89cb9c5880d144d4153265fe7e3e97e9fa1eea0ee02cbe7ce7bdda037888c11bd2d24f26c43b",
          "sha256": "3c2ff961a30f3a4562244c3aaf27bcadd67095f14c70ed4978638d825274f002",
          "sha1": "0394aa0285e4f81896151a39584c09284c967a4a",
          "md5": "fb68412a18169aaa56978cbb42da3ebd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-1-sources.jar",
          "url": "aerogel-gradle-plugin-26.2-1-sources.jar",
          "size": 30488,
          "sha512": "ea2488a8a9eda1a764141321d2c59ce3f51c25620697c5e602a16cc0a297c8c44e5a7da5601428d73f15e822efc2d37a29781173e7e3c1668f800f346949c1f6",
          "sha256": "eb434c494e386b26027734ce111a1936650e47224efea731c846d6d241fb8706",
          "sha1": "6b01f9bc7e3aa7eec927d2580f57ed60bf090ba8",
          "md5": "eb1f84517bd08fc094a74f9d461ac3b0"
        }
      ]
    }
  ]
}
