{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aerogel",
    "module": "aerogel-gradle-plugin",
    "version": "26.2-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-1.jar",
          "url": "aerogel-gradle-plugin-26.2-1.jar",
          "size": 80775,
          "sha512": "0aea206272194589b208238a531087691e3ab2d34871ba6cc7c7bb90ba63434e7d234321965e1d3d8e710be0c22655e5f139e82e87577000f0786deebbad7f74",
          "sha256": "6b78f59fc29d30f11db489aec25cdc132d449990095c5d2cea8e0a07fd71d907",
          "sha1": "65c8f9417f4cba004b14e69e823b7e799c26ca9e",
          "md5": "73d704a0389280328ef95e0c08f5bc7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.aerogel",
          "module": "aerogel-api",
          "version": {
            "requires": "26.2-1"
          }
        },
        {
          "group": "dev.aerogel",
          "module": "aerogel-mixin-dsl",
          "version": {
            "requires": "26.2-1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-1.jar",
          "url": "aerogel-gradle-plugin-26.2-1.jar",
          "size": 80775,
          "sha512": "0aea206272194589b208238a531087691e3ab2d34871ba6cc7c7bb90ba63434e7d234321965e1d3d8e710be0c22655e5f139e82e87577000f0786deebbad7f74",
          "sha256": "6b78f59fc29d30f11db489aec25cdc132d449990095c5d2cea8e0a07fd71d907",
          "sha1": "65c8f9417f4cba004b14e69e823b7e799c26ca9e",
          "md5": "73d704a0389280328ef95e0c08f5bc7e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-1-sources.jar",
          "url": "aerogel-gradle-plugin-26.2-1-sources.jar",
          "size": 29957,
          "sha512": "d480daa77d61509b210392854c02c8607debe4bb25bea857c7fe982103e5f8630ceea77b24f422ab05b9963cd903db2687981a0c4f03a60e7b9d32b49132531f",
          "sha256": "ae1661755a2f70b9ea17511291b76f0805a17dadd13e67140849f913950ca60f",
          "sha1": "9cd3ef3ae2033964c4dbf56a235d89738af9bb95",
          "md5": "39a80b749e0314faa5b73b0d340b1ff7"
        }
      ]
    }
  ]
}
