{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aerogel",
    "module": "aerogel-gradle-plugin",
    "version": "26.2-19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-19.jar",
          "url": "aerogel-gradle-plugin-26.2-19.jar",
          "size": 81977,
          "sha512": "8a6828c1691ad674580bdf0348e335634c2670a6efa28a57bd738b059c74c5a7259424e19ee773ef2ca57bd9eed43baea160a7e83de5faca4188d0c41b28ee3d",
          "sha256": "555fc1a85f5936299b34bcc39eb6fb36b1f523df1814d30a7d965f29eafac500",
          "sha1": "35b3057ae54f02737dba4b850f84929a258b4861",
          "md5": "60d73e2f8978aa13a33baebbd67f45c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.aerogel",
          "module": "aerogel-api",
          "version": {
            "requires": "26.2-19"
          }
        },
        {
          "group": "dev.aerogel",
          "module": "aerogel-mixin-dsl",
          "version": {
            "requires": "26.2-19"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-19.jar",
          "url": "aerogel-gradle-plugin-26.2-19.jar",
          "size": 81977,
          "sha512": "8a6828c1691ad674580bdf0348e335634c2670a6efa28a57bd738b059c74c5a7259424e19ee773ef2ca57bd9eed43baea160a7e83de5faca4188d0c41b28ee3d",
          "sha256": "555fc1a85f5936299b34bcc39eb6fb36b1f523df1814d30a7d965f29eafac500",
          "sha1": "35b3057ae54f02737dba4b850f84929a258b4861",
          "md5": "60d73e2f8978aa13a33baebbd67f45c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-19-sources.jar",
          "url": "aerogel-gradle-plugin-26.2-19-sources.jar",
          "size": 30550,
          "sha512": "1ee76b029a41fa81a311b97a5b7b0f8b4224911ada63187ba716dc92ffe4c982a44842cec1edbdb413443d73d07cfa8ace9723d30a5a5c6b74ddc01e23331299",
          "sha256": "65c2ab44f0df2d98bb793322e1e0c2f3e7922ca2af9e602727f4789201e27289",
          "sha1": "4c89d0ceec314f78f8e04756a557f470608408a8",
          "md5": "9a6c8402882de39538a32f78fd8ea77a"
        }
      ]
    }
  ]
}
