{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aerogel",
    "module": "aerogel-gradle-plugin",
    "version": "26.2-7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-7.jar",
          "url": "aerogel-gradle-plugin-26.2-7.jar",
          "size": 81976,
          "sha512": "2a27c823e2e549df156858b3120733a88197ddbd1fcdc349f8dec73e4eeec15e5a27f167ce38658160da142c7ee305a3d4ef057342db409379bcaf0261e373ed",
          "sha256": "3bab4609abddfa338f23f7accb8a76d7f9a3fa8eb9c285169f02af1c43dbb0f5",
          "sha1": "8a014510619a87d03fce6714d4df97977c76b6e0",
          "md5": "0690d54e8d985515ebb568792ade9811"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.aerogel",
          "module": "aerogel-api",
          "version": {
            "requires": "26.2-7"
          }
        },
        {
          "group": "dev.aerogel",
          "module": "aerogel-mixin-dsl",
          "version": {
            "requires": "26.2-7"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-7.jar",
          "url": "aerogel-gradle-plugin-26.2-7.jar",
          "size": 81976,
          "sha512": "2a27c823e2e549df156858b3120733a88197ddbd1fcdc349f8dec73e4eeec15e5a27f167ce38658160da142c7ee305a3d4ef057342db409379bcaf0261e373ed",
          "sha256": "3bab4609abddfa338f23f7accb8a76d7f9a3fa8eb9c285169f02af1c43dbb0f5",
          "sha1": "8a014510619a87d03fce6714d4df97977c76b6e0",
          "md5": "0690d54e8d985515ebb568792ade9811"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aerogel-gradle-plugin-26.2-7-sources.jar",
          "url": "aerogel-gradle-plugin-26.2-7-sources.jar",
          "size": 30550,
          "sha512": "1ee76b029a41fa81a311b97a5b7b0f8b4224911ada63187ba716dc92ffe4c982a44842cec1edbdb413443d73d07cfa8ace9723d30a5a5c6b74ddc01e23331299",
          "sha256": "65c2ab44f0df2d98bb793322e1e0c2f3e7922ca2af9e602727f4789201e27289",
          "sha1": "4c89d0ceec314f78f8e04756a557f470608408a8",
          "md5": "9a6c8402882de39538a32f78fd8ea77a"
        }
      ]
    }
  ]
}
